Gameblasts: Gameblasts.Controllers.AccountController Class Reference
Gameblasts.Controllers.AccountController Class Reference
Public Member Functions
AccountController (UserManager< ApplicationUser > userManager, SignInManager< ApplicationUser > signInManager, IOptions< IdentityCookieOptions > identityCookieOptions, IEmailSender emailSender, ISmsSender smsSender, ILoggerFactory loggerFactory)
async Task< IActionResult > Login (string returnUrl=null)
async Task< IActionResult > Login (LoginViewModel model, string returnUrl=null)
IActionResult Register (string returnUrl=null)
async Task< IActionResult > Register (RegisterViewModel model, string returnUrl=null)
async Task< IActionResult > Logout ()
IActionResult ExternalLogin (string provider, string returnUrl=null)
async Task< IActionResult > ExternalLoginCallback (string returnUrl=null, string remoteError=null)
async Task< IActionResult > ExternalLoginConfirmation (ExternalLoginConfirmationViewModel model, string returnUrl=null)
async Task< IActionResult > ConfirmEmail (string userId, string code)
IActionResult ForgotPassword ()
async Task< IActionResult > ForgotPassword (ForgotPasswordViewModel model)
IActionResult ForgotPasswordConfirmation ()
IActionResult ResetPassword (string code=null)
async Task< IActionResult > ResetPassword (ResetPasswordViewModel model)
IActionResult ResetPasswordConfirmation ()
async Task< ActionResult > SendCode (string returnUrl=null, bool rememberMe=false)
async Task< IActionResult > SendCode (SendCodeViewModel model)
async Task< IActionResult > VerifyCode (string provider, bool rememberMe, string returnUrl=null)
async Task< IActionResult > VerifyCode (VerifyCodeViewModel model)
IActionResult AccessDenied ()
Detailed Description
Definition at line 17 of file AccountController.cs.
Constructor & Destructor Documentation
AccountController()
Gameblasts.Controllers.AccountController.AccountController (UserManager< ApplicationUser > userManager, SignInManager< ApplicationUser > signInManager, IOptions< IdentityCookieOptions > identityCookieOptions, IEmailSender emailSender, ISmsSender smsSender, ILoggerFactory loggerFactory)
Definition at line 26 of file AccountController.cs.
Member Function Documentation
AccessDenied()
IActionResult Gameblasts.Controllers.AccountController.AccessDenied ()
Definition at line 448 of file AccountController.cs.
References Gameblasts.Controllers.HomeController.Index().
ConfirmEmail()
async Task<IActionResult> Gameblasts.Controllers.AccountController.ConfirmEmail (string userId, string code)
Definition at line 238 of file AccountController.cs.
ExternalLogin()
IActionResult Gameblasts.Controllers.AccountController.ExternalLogin (string provider, string returnUrl = null)
Definition at line 151 of file AccountController.cs.
ExternalLoginCallback()
async Task<IActionResult> Gameblasts.Controllers.AccountController.ExternalLoginCallback (string returnUrl = null, string remoteError = null)
Definition at line 163 of file AccountController.cs.
ExternalLoginConfirmation()
async Task<IActionResult> Gameblasts.Controllers.AccountController.ExternalLoginConfirmation (ExternalLoginConfirmationViewModel model, string returnUrl = null)
Definition at line 206 of file AccountController.cs.
References Gameblasts.Models.AccountViewModels.ExternalLoginConfirmationViewModel.Email.
ForgotPassword() [1/2]
IActionResult Gameblasts.Controllers.AccountController.ForgotPassword ()
Definition at line 257 of file AccountController.cs.
ForgotPassword() [2/2]
async Task<IActionResult> Gameblasts.Controllers.AccountController.ForgotPassword (ForgotPasswordViewModel model)
Definition at line 267 of file AccountController.cs.
References Gameblasts.Models.AccountViewModels.ForgotPasswordViewModel.Email.
ForgotPasswordConfirmation()
IActionResult Gameblasts.Controllers.AccountController.ForgotPasswordConfirmation ()
Definition at line 295 of file AccountController.cs.
Login() [1/2]
async Task<IActionResult> Gameblasts.Controllers.AccountController.Login (string returnUrl = null)
Definition at line 46 of file AccountController.cs.
Login() [2/2]
async Task<IActionResult> Gameblasts.Controllers.AccountController.Login (LoginViewModel model, string returnUrl = null)
Definition at line 60 of file AccountController.cs.
References Gameblasts.Models.AccountViewModels.LoginViewModel.Password, Gameblasts.Models.AccountViewModels.LoginViewModel.RememberMe, and Gameblasts.Models.AccountViewModels.LoginViewModel.Username.
Logout()
async Task<IActionResult> Gameblasts.Controllers.AccountController.Logout ()
Definition at line 139 of file AccountController.cs.
References Gameblasts.Controllers.HomeController.Index().
Register() [1/2]
IActionResult Gameblasts.Controllers.AccountController.Register (string returnUrl = null)
Definition at line 97 of file AccountController.cs.
Register() [2/2]
async Task<IActionResult> Gameblasts.Controllers.AccountController.Register (RegisterViewModel model, string returnUrl = null)
Definition at line 108 of file AccountController.cs.
References Gameblasts.Models.AccountViewModels.RegisterViewModel.Email, Gameblasts.Models.AccountViewModels.RegisterViewModel.Password, and Gameblasts.Models.AccountViewModels.RegisterViewModel.UserName.
ResetPassword() [1/2]
IActionResult Gameblasts.Controllers.AccountController.ResetPassword (string code = null)
Definition at line 304 of file AccountController.cs.
ResetPassword() [2/2]
async Task<IActionResult> Gameblasts.Controllers.AccountController.ResetPassword (ResetPasswordViewModel model)
Definition at line 314 of file AccountController.cs.
References Gameblasts.Models.AccountViewModels.ResetPasswordViewModel.Code, Gameblasts.Models.AccountViewModels.ResetPasswordViewModel.Email, Gameblasts.Models.AccountViewModels.ResetPasswordViewModel.Password, and Gameblasts.Controllers.AccountController.ResetPasswordConfirmation().
ResetPasswordConfirmation()
IActionResult Gameblasts.Controllers.AccountController.ResetPasswordConfirmation ()
Definition at line 339 of file AccountController.cs.
Referenced by Gameblasts.Controllers.AccountController.ResetPassword().
SendCode() [1/2]
async Task<ActionResult> Gameblasts.Controllers.AccountController.SendCode (string returnUrl = null, bool rememberMe = false)
Definition at line 348 of file AccountController.cs.
SendCode() [2/2]
async Task<IActionResult> Gameblasts.Controllers.AccountController.SendCode (SendCodeViewModel model)
Definition at line 365 of file AccountController.cs.
References Gameblasts.Models.AccountViewModels.SendCodeViewModel.RememberMe, Gameblasts.Models.AccountViewModels.SendCodeViewModel.ReturnUrl, and Gameblasts.Models.AccountViewModels.SendCodeViewModel.SelectedProvider.
VerifyCode() [1/2]
async Task<IActionResult> Gameblasts.Controllers.AccountController.VerifyCode (string provider, bool rememberMe, string returnUrl = null)
Definition at line 402 of file AccountController.cs.
VerifyCode() [2/2]
async Task<IActionResult> Gameblasts.Controllers.AccountController.VerifyCode (VerifyCodeViewModel model)
Definition at line 418 of file AccountController.cs.
References Gameblasts.Models.AccountViewModels.VerifyCodeViewModel.Code, Gameblasts.Models.AccountViewModels.VerifyCodeViewModel.Provider, Gameblasts.Models.AccountViewModels.VerifyCodeViewModel.RememberBrowser, Gameblasts.Models.AccountViewModels.VerifyCodeViewModel.RememberMe, and Gameblasts.Models.AccountViewModels.VerifyCodeViewModel.ReturnUrl.
The documentation for this class was generated from the following file:
Controllers/AccountController.cs