Gameblasts: Gameblasts.Startup Class Reference
Gameblasts.Startup Class Reference
Public Member Functions
Startup (IHostingEnvironment env)
void ConfigureServices (IServiceCollection services)
void ConfigureDevelopmentServices (IServiceCollection services)
async Task CreateUsersAndRoles (IServiceScope serviceScope)
void CreateCategories (ApplicationDbContext db, string topCatName, string logoURL=null, string imageURL=null)
void Configure (IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
Properties
IConfigurationRoot Configuration [get]
Detailed Description
Definition at line 18 of file Startup.cs.
Constructor & Destructor Documentation
Startup()
Gameblasts.Startup.Startup (IHostingEnvironment env)
Definition at line 20 of file Startup.cs.
References Gameblasts.Startup.Configuration.
Member Function Documentation
Configure()
void Gameblasts.Startup.Configure (IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
Definition at line 188 of file Startup.cs.
References Gameblasts.Startup.Configuration, Gameblasts.Startup.CreateCategories(), and Gameblasts.Startup.CreateUsersAndRoles().
ConfigureDevelopmentServices()
void Gameblasts.Startup.ConfigureDevelopmentServices (IServiceCollection services)
Definition at line 58 of file Startup.cs.
References Gameblasts.Startup.Configuration.
ConfigureServices()
void Gameblasts.Startup.ConfigureServices (IServiceCollection services)
Definition at line 40 of file Startup.cs.
References Gameblasts.Startup.Configuration.
CreateCategories()
void Gameblasts.Startup.CreateCategories (ApplicationDbContext db, string topCatName, string logoURL = null, string imageURL = null)
Definition at line 161 of file Startup.cs.
References Gameblasts.Data.ApplicationDbContext.Categories.
Referenced by Gameblasts.Startup.Configure().
CreateUsersAndRoles()
async Task Gameblasts.Startup.CreateUsersAndRoles (IServiceScope serviceScope)
Definition at line 78 of file Startup.cs.
Referenced by Gameblasts.Startup.Configure().
Property Documentation
Configuration
IConfigurationRoot Gameblasts.Startup.Configuration get
Definition at line 37 of file Startup.cs.
Referenced by Gameblasts.Startup.Configure(), Gameblasts.Startup.ConfigureDevelopmentServices(), Gameblasts.Startup.ConfigureServices(), and Gameblasts.Startup.Startup().
The documentation for this class was generated from the following file:
Startup.cs